# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
