# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171025_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='username',
        ),
    ]
