# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171026_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
