# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20171026_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
