# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20171026_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.CharField(default='01011997', max_length=8),
        ),
    ]
