# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_student_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateofbirth',
            field=models.CharField(max_length=8),
        ),
    ]
