# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171026_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
