drop database institute;
create database institute;
use institute;
create table student(student_id int not null auto_increment primary key, name char(100), mobile char(10), dateofbirth char(8) not null, address char(100), father_name char(100), mother_name char(100), standard int, school char(100));
create table teacher(teacher_id int not null auto_increment primary key, password char(100) not null, name char(100), mobile char(10), dateofbirth date, address char(100));
create table classroom(room_id int not null auto_increment primary key, hall_name char(100), capacity int);
create table batch(batch_id int not null auto_increment primary key, standard int, subject char(100), teacher_id int, foreign key (teacher_id) references teacher(teacher_id) on delete cascade, room_id int, foreign key(room_id) references classroom(room_id) on delete cascade, fee int);
create table discussion_page(page_id int not null auto_increment primary key, batch_id int, foreign key (batch_id) references batch(batch_id) on delete cascade);
create table time_slot(timeslot_id int not null auto_increment primary key, day char(10), start_time float, end_time float);
create table batch_timeslot(batch_id int, foreign key (batch_id) references batch(batch_id) on delete cascade, timeslot_id int, foreign key (timeslot_id) references time_slot(timeslot_id) on delete cascade, primary key(batch_id,timeslot_id));
create table joins(student_id int, foreign key (student_id) references student(student_id) on delete cascade, batch_id int, foreign key (batch_id) references batch(batch_id) on delete cascade, primary key(student_id,batch_id));
create table comment(comment_id int auto_increment primary key, page_id int, foreign key (page_id) references discussion_page(page_id) on delete cascade, statement text, name char(100), timedate datetime);
create table attendance(student_id int, batch_id int, foreign key (student_id,batch_id) references joins(student_id,batch_id) on delete cascade, dateofclass date, record char(1), primary key(student_id, batch_id, dateofclass));
create table fee(receipt_id int not null auto_increment primary key, amount int, dateofdeposit date, student_id int, batch_id int, foreign key (student_id,batch_id) references joins(student_id,batch_id) on delete cascade);


insert into student(name,mobile,dateofbirth,address,father_name,mother_name,standard,school) values('Saurabh','9657965513','24081997','Shivaji Colony','Bhagirath','Sarla',10,'Saint Paul');
insert into teacher(password, name, mobile, dateofbirth, address) values('qwerty12', 'Bhagirath', '1234', '1963-11-19', 'shivaji');
insert into classroom(hall_name,capacity) values('gf hall', 120);
insert into batch(standard, subject, teacher_id, room_id, fee) values(10, 'Maths', 1, 1, 1000);
insert into discussion_page(batch_id) values(1);
insert into joins(student_id, batch_id) values(1,1);
insert into time_slot(day, start_time, end_time) values('MON',8,9);
insert into batch_timeslot(batch_id,timeslot_id) values(1,1);
insert into attendance(student_id, batch_id, dateofclass, record) values (1,1,'2017-07-25','A');
insert into fee(amount,dateofdeposit,student_id,batch_id) values(200, '2017-07-01',1,1);
insert into comment(page_id, statement, name, timedate) values(1,'Why speed of light is 3*10^8 m/s', 'Saurabh Rathi' , now());

insert into time_slot(day, start_time, end_time) values('TUE',8,9);
insert into time_slot(day, start_time, end_time) values('WED',8,9);
insert into time_slot(day, start_time, end_time) values('THUR',8,9);
insert into time_slot(day, start_time, end_time) values('FRI',8,9);
insert into time_slot(day, start_time, end_time) values('SAT',8,9);
insert into batch_timeslot(batch_id,timeslot_id) values(1,3);
insert into batch_timeslot(batch_id,timeslot_id) values(1,5);
insert into attendance(student_id, batch_id, dateofclass, record) values (1,1,'2017-07-26','P');
insert into attendance(student_id, batch_id, dateofclass, record) values (1,1,'2017-07-27','P');
insert into attendance(student_id, batch_id, dateofclass, record) values (1,1,'2017-08-01','P');
insert into attendance(student_id, batch_id, dateofclass, record) values (1,1,'2017-08-02','P');
insert into fee(amount,dateofdeposit,student_id,batch_id) values(200, '2017-08-01',1,1);